=== USF-COT/LirLogger/LirConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="LirConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OutputFolder" type="xs:string"/>
                <xs:element name="GigECamera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MACAddress" type="xs:string"/>
                            <xs:element name="BufferLength" type="xs:positiveInteger" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="EthernetSensor" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="IPAddress" type="xs:string"/>
                            <xs:element name="Port" type="xs:positiveInteger"/>
                            <xs:element name="StartChars" type="xs:string"/>
                            <xs:element name="EndChars" type="xs:string"/>
                            <xs:element name="Delimeter" type="xs:string"/>
                            <xs:element name="LineEnd" type="xs:string"/>
                            <xs:element name="Fields">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Field" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="numeric" type="xs:boolean" default="false"/>
                                                <xs:attribute name="name" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== USF-COT/LirLogger/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<LirConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="LirConfigSchema.xsd">
    <OutputFolder>/archives/test</OutputFolder>
    <GigECamera>
        <MACAddress>00-11-1c-f0-0f-09</MACAddress>
        <BufferLength>16</BufferLength>
    </GigECamera>
    <EthernetSensor>
        <Name>AMLCTD</Name>
        <IPAddress>131.247.138.19</IPAddress>
        <Port>4000</Port>
        <StartChars></StartChars>
        <EndChars></EndChars>
        <Delimeter> </Delimeter>
        <LineEnd>\r\n</LineEnd>
        <Fields>
            <Field numeric="true" name="conductivity"/>
            <Field numeric="true" name="pressure"/>
            <Field numeric="true" name="temperature"/>
            <Field numeric="true" name="voltage"/>
            <Field numeric="true" name="salinity"/>
        </Fields>
    </EthernetSensor>
</LirConfig>
